version: 2.1

jobs:
  # Build the Docker image
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Checkout merge commit
          command: |
            set -ex
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]
            then
              FETCH_REFS="${FETCH_REFS}
              +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"
              git fetch -u origin ${FETCH_REFS}
              git checkout "pr/${CIRCLE_PR_NUMBER}/merge"
            fi
      - run:
          name: Checking out submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Install LDC
          command: |
            mkdir -p $HOME/dlang && wget https://dlang.org/install.sh -O $HOME/dlang/install.sh
            chmod +x $HOME/dlang/install.sh
            $HOME/dlang/install.sh install ldc-1.20.1
      - run:
          name: Install libsodium
          command: |
            pushd $HOME
            wget https://github.com/jedisct1/libsodium/archive/1.0.18-RELEASE.tar.gz
            tar xvfz 1.0.18-RELEASE.tar.gz
            cd libsodium-1.0.18-RELEASE
            ./configure
            make -j4
            sudo make install
            sudo ldconfig # Refresh cache
            popd
      - run:
          name: Build & test docker image
          command: |
            source $HOME/dlang/ldc-1.20.1/activate
            ci/system_integration_test.d
            # Work around druntime setting the permissions to 600..
            sudo chmod 644 tests/system/node/*/*.lst
          no_output_timeout: 15m
      - run:
          name: Upload code coverage
          command: |
             curl -s https://codecov.io/bash | bash -s -- \
               -n "CircleCI" -F "integration" -Z || echo 'Codecov upload failed'
