#
# This configuration file is intended to provide a standalone local network
# with a single validator.
#
# This configuration is provided for the convenience of developers and should
# not be used in production. See `doc/config.example.yaml` for a full,
# up to date example of the configuration options available
#
# Run from the root with:
# ./build/agora -c devel/config-single.yaml

node:
  testing: true
  limit_test_validators: 1
  data_dir: .single/data/
  # Can be used with curl or just a browser
  stats_listening_port: 9111

interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826

consensus:
  block_interval_sec: 5
  validator_cycle: 20

validator:
  enabled: true
  # We use first of Genesis Block enrollments: val7: boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh
  seed: SAWI3JZWDDSQR6AX4DRG2OMS26Y6XY4X2WA3FK6D5UW4WTU74GUQXRZP
  registry_address: disabled

admin:
  enabled: true
  address: 0.0.0.0
  port:    2827

# The node will self-ban but this section needs at least one entry
network:
  - http://127.0.0.1:2826/

logging:
  root:
    level: Info
    console: true
  # agora:
  #   level: Trace
  #   console: false
  #   file: .single/log/agora.log
