# Inspired from https://github.com/actions/starter-workflows/blob/main/automation/manual.yml

# Will tag the provided release as `latest` in Docker hub
name: Update Docker latest tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g. v1.0.0)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set ${{ github.event.inputs.tag }} as latest
        uses: akhilerm/tag-push-action@v1.1.0
        with:
          src: docker.io/bpfk/agora:${{ github.event.inputs.tag }}
          dst: docker.io/bpfk/agora:latest
