name: Build and publish release image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    # https://github.com/actions/runner/issues/953#issuecomment-821537265
    env:
      HAVE_DOCKERHUB_SECRET: ${{ secrets.DOCKERHUB_TOKEN != '' && secrets.DOCKERHUB_USERNAME != '' }}
    steps:
      - name: Get version number
        shell: bash
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        id: login
        # If the user set up those variable, it's upstream or (s)he wants the push to happen
        # Otherwise, it might just be someone pushing to their fork, in which case we still
        # want to build as it's useful to test a release before upstreaming it.
        if: env.HAVE_DOCKERHUB_SECRET
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # This step will checkout the source with all the submodules
      - name: '[Agora] Build and push'
        uses: docker/build-push-action@v2
        with:
          # Either 'success' or 'skipped'
          push: ${{ steps.login.outcome == 'success' }}
          tags: bosagora/agora:${{ steps.version.outputs.VERSION }}
          build-args: |
            AGORA_VERSION=${{ steps.version.outputs.VERSION }}
